export const messageMap: Record<string, string> = {
  'successGetList': '查询成功',
  'successAdd': '添加成功',
  'successUpdate': '更新成功',
  'successDelete': '删除成功',
  'successLogin': '登录成功',
  'successLogout': '退出成功',
  'successRegister': '注册成功',
  'successResetPassword': '重置密码成功',
  'failGetList': '查询失败',
  'failAdd': '添加失败',
  'failUpdate': '更新失败',
  'failDelete': '删除失败',
  'failLogin': '登录失败',
  'failLogout': '退出失败',
  'failRegister': '注册失败',
  'failResetPassword': '重置密码失败',
  'success': '操作成功',
  'fail': '操作失败',
}